### ISSUE TITLE
[Dataset] How to create the dataset with my own photos？

### ISSUE THREAD

**Issue by xdobetter** [YuliangXiu/PuzzleAvatar#5]
Hi, very interesting project. I ran your project, and it was great！
But I have some questions: how do I make my own dataset to fit your project?

**Comment by YuliangXiu** [comment]
For testing, you can use any photos with the same clothing, please refer to `wget https://download.is.tue.mpg.de/icon/human.zip` to see the photos I used to create the teaser

To benchmark, you need to prepare the photos, together with the A-posed textured scans (incl. A-posed SMPL-X)

**Comment by xdobetter** [comment]
I appreciate your help and I have successfully run it on my own data. I have an additional question. The content in my current gpt4v_simple.json is obtained by querying ChatGPT-4o using the prompt provided in the paper. Do you have a corresponding script in your project to obtain this content?

**Comment by YuliangXiu** [comment]
Okay, I noticed that I failed to upload the `gpt4v_complex.txt` and `gpt4v_simple.txt` files due to `.gitignore`. I will update them tonight, and let you know.

**Comment by xdobetter** [comment]
> Is [grounding_dino_sam.py#L219](https://github.com/YuliangXiu/PuzzleAvatar/blob/main/multi_concepts/grounding_dino_sam.py#L219) what you asked for? The `gpt4v_simple.json` should be there if you run `grounding_dino_sam.py` as in [run.sh#L12](https://github.com/YuliangXiu/PuzzleAvatar/blob/main/scripts/run.sh#L12)

Yes, that's exactly what I want to ask. I use the [gpt4v_prompt.txt](https://github.com/YuliangXiu/PuzzleAvatar/blob/main/multi_concepts/gpt4v_prompt.txt) you provided instead of gpt4v_simple.txt, which can automatically generate gpt4v_simple.json. I don't know if your code is a bug in the line https://github.com/YuliangXiu/PuzzleAvatar/blob/e1d46171f3f8cdada56b22d556f2cdfc291f446f/multi_concepts/grounding_dino_sam.py#L219
