### ISSUE TITLE
这环境有点儿太难配了

### ISSUE THREAD

**Issue by jim-1ee** [YuliangXiu/PuzzleAvatar#9]

**Comment by YuliangXiu** [comment]
There have been many successful runs and a few commits to resolve minor issues.

PuzzleAvatar shares the same environment as [TeCH](https://github.com/huangyangyi/TeCH/blob/main/docs/install.md#if-you-still-struggle-with-the-package-conflict-yuliangxiutech-shows-a-cleaner-version-to-setup-tech-at-ubuntu-22043-lts-nvidia-a100-80g-cuda117-with-anaconda-this-forked-repository-has-removed-almost-all-the-package-version-requirements-see-requirementstxt).

Once set up, you can run both baselines (PuzzleAvatar, TeCH) effortlessly. Be brave—just do it!
